{% set name = "bleach" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bleach-{{ version }}.tar.gz
  sha256: 123e894118b8a599fd80d3ec1a6d4cc7ce4e5882b1317a7e1ba69b56e95f991f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - webencodings

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - bleach

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - bleach/_vendor/html5lib-1.1.dist-info/LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
  description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or
    strips markup and attributes.
  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/
  doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
